### ISSUE TITLE
Problem of Inchi reading

### ISSUE THREAD

**Issue by Pmicheau** [stanstrup/PredRet#71]
My file looks to be in a good format (CSV format, coma separator, text value beetween quoted) and looks to be correctly read. In the menu "manage your data" I see properly my list of compounds (right name, right retention time...). The problem is that I see always the same Inchi for all my compounds instead of one inchi for each compounds. Is it a problem of coding / programming ? Is it a bug ? Could you fix the problem ? I do many test to try to solve the problem but without success.

Thanks for your help.

Regards

**Comment by stanstrup** [comment]
Hi,

I just discovered this bug the other day myself. The bug is triggered by incorrect inchi's that can't be parsed. If some of them are ok then it simply puts that for all of them. It is a problem of using obabel directly that doesn't warn when it discards invalid inputs. The real fix is getting rid of obabel which will be difficult. 

I can try to put in a check for this but to get your compound in correctly you need correct inchis. Can you send me the CSV so I can try to see if I can see what the problem is?
